### ISSUE TITLE
SolverError: Either candidate conic solvers (['CVXOPT']) do not support the cones output by the problem (ExpCone), or there are not enough constraints in the problem.

### ISSUE THREAD

**Issue by touxiaoling** [planetlabs/maxrect#7]
hello,i just Installation this use
```
pip install git+https://${GITHUB_TOKEN}@github.com/planetlabs/maxrect.git
```
and run some test code :
 ```python
from maxrect import get_intersection, get_maximal_rectangle, rect2poly

# For a given convex polygon
coordinates1 = [[0,0],[0,1287.206-527.796],[1576.252,1287.206],[1815.126,1287.206],[0,0]]


# get the maximally inscribed rectangle
ll, ur = get_maximal_rectangle(coordinates1)

# casting the rectangle to a GeoJSON-friendly closed polygon
rect2poly(ll, ur)
```
but there have some error 
```
(base) tomin@ubuntu:~/python$ /home/tomin/anaconda3/bin/python /home/tomin/python/test.py
Traceback (most recent call last):
  File "/home/tomin/python/test.py", line 8, in <module>
    ll, ur = get_maximal_rectangle(coordinates1)
  File "/home/tomin/anaconda3/lib/python3.7/site-packages/maxrect/__init__.py", line 139, in get_maximal_rectangle
    prob.solve(solver=cvxpy.CVXOPT, verbose=False, max_iters=1000, reltol=1e-9)
  File "/home/tomin/anaconda3/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 290, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/tomin/anaconda3/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 568, in _solve
    self._construct_chains(solver=solver, gp=gp)
  File "/home/tomin/anaconda3/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 511, in _construct_chains
    raise e
  File "/home/tomin/anaconda3/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 497, in _construct_chains
    gp=gp)
  File "/home/tomin/anaconda3/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 434, in _find_candidate_solvers
    raise error.SolverError("The solver %s is not installed." % solver)
cvxpy.error.SolverError: The solver CVXOPT is not installed.
```
so i use conda install cvxopt
```
conda install CVXOPT
```
but there have some new errors
```
(base) tomin@ubuntu:~/python$ /home/tomin/anaconda3/bin/python /home/tomin/python/test.py
Traceback (most recent call last):
  File "/home/tomin/python/test.py", line 8, in <module>
    ll, ur = get_maximal_rectangle(coordinates1)
  File "/home/tomin/anaconda3/lib/python3.7/site-packages/maxrect/__init__.py", line 139, in get_maximal_rectangle
    prob.solve(solver=cvxpy.CVXOPT, verbose=False, max_iters=1000, reltol=1e-9)
  File "/home/tomin/anaconda3/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 290, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/tomin/anaconda3/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 568, in _solve
    self._construct_chains(solver=solver, gp=gp)
  File "/home/tomin/anaconda3/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 511, in _construct_chains
    raise e
  File "/home/tomin/anaconda3/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 506, in _construct_chains
    candidate_solvers)
  File "/home/tomin/anaconda3/lib/python3.7/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 97, in construct_solving_chain
    ", ".join([cone.__name__ for cone in cones])))
cvxpy.error.SolverError: Either candidate conic solvers (['CVXOPT']) do not support the cones output by the problem (ExpCone), or there are not enough constraints in the problem.
```
can you help me ?thanks!

**Comment by touxiaoling** [comment]
i maybe solve this problem.
go to read :
https://www.cvxpy.org/tutorial/advanced/index.html#solvers
there have some info:
> Here EXP refers to problems with exponential cone constraints. The exponential cone is defined as
>{(x,y,z)∣y>0,yexp(x/y)≤z}∪{(x,y,z)∣x≤0,y=0,z≥0}.
>Most users will never specify cone constraints directly. Instead, cone constraints are added when CVXPY converts the problem into standard form.
>By default CVXPY calls the solver most specialized to the problem type.

so i change the code in _init_.py at line 139
```python
prob.solve(solver=cvxpy.CVXOPT, verbose=False, max_iters=1000, reltol=1e-9)
```
to
```python
prob.solve()
```
now,it work.maybe there still have some problem,but it can be run.

**Comment by robbiemu** [comment]
found I also needed to change the return:
```py
    #return list(bottom_left[0]), list(top_right[0])
    return bottom_left, top_right
```

the original was erroring. 

_pull request of the same: https://github.com/planetlabs/maxrect/pull/8_


With that you can go from-to shapely like:
```py
def maximize_rectangle(S: Polygon):
    pa = get_maximal_rectangle(S.exterior.coords)
    return Polygon([(pa[0][0],pa[0][1]), (pa[0][0],pa[1][1]), (pa[1][0],pa[1][1]), (pa[1][0],pa[0][1])])
```

**Comment by Aurbcd** [comment]
Still have the same issue even if I did the same manipulation. Anybody have the same problem ?

> i maybe solve this problem. go to read : https://www.cvxpy.org/tutorial/advanced/index.html#solvers there have some info:
> 
> > Here EXP refers to problems with exponential cone constraints. The exponential cone is defined as
> > {(x,y,z)∣y>0,yexp(x/y)≤z}∪{(x,y,z)∣x≤0,y=0,z≥0}.
> > Most users will never specify cone constraints directly. Instead, cone constraints are added when CVXPY converts the problem into standard form.
> > By default CVXPY calls the solver most specialized to the problem type.
> 
> so i change the code in _init_.py at line 139
> 
> ```python
> prob.solve(solver=cvxpy.CVXOPT, verbose=False, max_iters=1000, reltol=1e-9)
> ```
> 
> to
> 
> ```python
> prob.solve()
> ```
> 
> now,it work.maybe there still have some problem,but it can be run.
